# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        aws_uploads_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: "%env(AWS_S3_ACCESS_BUCKET)%"
                prefix: storage
        public_uploads_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'
    filesystems:
        public_uploads_filesystem:
            adapter: aws_uploads_adapter
            alias: League\Flysystem\Filesystem
